import { StyleSheet } from "react-native";

import { COLORS } from "../../lib/colors";

export const styles = StyleSheet.create({
  gradient: { flex: 1 },
  container: { flex: 1 },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 24,
    paddingVertical: 40,
  },
  card: {
    backgroundColor: COLORS.surface,
    borderRadius: 20,
    padding: 32,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 8,
  },
  logoContainer: { alignItems: "center", marginBottom: 8 },
  logoCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: COLORS.violetSoft,
    justifyContent: "center",
    alignItems: "center",
  },
  logoEmoji: { fontSize: 36 },
  title: { fontSize: 28, fontWeight: "800", color: COLORS.brandDeep, textAlign: "center" },
  subtitle: {
    fontSize: 15,
    color: COLORS.textSecondary,
    textAlign: "center",
    marginBottom: 28,
    marginTop: 4,
  },
  errorBox: {
    backgroundColor: COLORS.dangerSoft,
    borderWidth: 1,
    borderColor: COLORS.dangerBorder,
    borderRadius: 10,
    padding: 12,
    marginBottom: 16,
  },
  errorText: { color: COLORS.danger, fontSize: 14, textAlign: "center" },
  inputGroup: { marginBottom: 16 },
  fieldErrorText: { color: COLORS.danger, fontSize: 12, marginTop: 6, marginLeft: 4 },
  inputLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.textSecondary,
    marginBottom: 6,
    marginLeft: 2,
  },
  input: {
    backgroundColor: COLORS.surfaceSoft,
    borderWidth: 1.5,
    borderColor: COLORS.borderMuted,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: COLORS.textPrimary,
  },
  inputFocused: {
    borderColor: COLORS.brandPrimary,
    backgroundColor: COLORS.surfaceHighlight,
    shadowColor: COLORS.brandPrimary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  button: { borderRadius: 12, marginTop: 8, overflow: "hidden" },
  buttonDisabled: { opacity: 0.6 },
  buttonGradient: { paddingVertical: 16, alignItems: "center" },
  buttonText: { color: COLORS.textOnBrand, fontSize: 16, fontWeight: "700" },
  switchLink: { marginTop: 20, alignItems: "center" },
  switchText: { fontSize: 14, color: COLORS.textSecondary },
  switchBold: { color: COLORS.brandPrimary, fontWeight: "700" },
});
