import { StyleSheet } from "react-native";

import { BRAND_FONT_FAMILY } from "../../lib/brand-font";
import type { AppColors } from "../../lib/colors";

export function makeCoursesListStyles(colors: AppColors) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.canvas },
    headerGradient: { 
      paddingTop: 48, 
      paddingBottom: 20, 
      paddingHorizontal: 20,
      elevation: 6,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
    },
    headerContent: {
      gap: 14,
      flexDirection: "column",
      justifyContent: "flex-start",
      alignItems: "flex-start",
    },
    brandRowContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      width: "100%",
    },
    brandUnit: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    brandMascot: {
      width: 58,
      height: 58,
    },
    brandTitle: {
      fontSize: 30,
      lineHeight: 36,
      color: colors.textOnBrand,
      fontFamily: BRAND_FONT_FAMILY,
      letterSpacing: 0.3,
      includeFontPadding: false,
    },
    brandTitleAccent: {
      color: colors.brandAccent,
    },
    brandSubtitle: {
      fontSize: 13,
      color: colors.textOnBrand,
      fontFamily: BRAND_FONT_FAMILY,
      fontWeight: "500",
      letterSpacing: 0.6,
      lineHeight: 18,
      includeFontPadding: false,
      opacity: 0.8,
      alignSelf: "flex-end",
      textAlign: "right",
    },
    aiChatButton: {
      backgroundColor: "rgba(255,255,255,0.22)", 
      width: 52, 
      height: 52, 
      borderRadius: 26, 
      justifyContent: "center", 
      alignItems: "center",
      borderWidth: 1.5,
      borderColor: "rgba(255,255,255,0.25)",
      shadowColor: "#fff",
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.15,
      shadowRadius: 6,
    },
    aiChatIcon: { 
      width: 44, 
      height: 44, 
      transform: [{ scale: 1.4 }] 
    },
    headerGreeting: { 
      fontSize: 12, 
      color: colors.textOnBrand, 
      fontWeight: "900",
      textTransform: "uppercase", 
      letterSpacing: 1.5,
      opacity: 0.8,
    },
    greetingRow: {
      flexDirection: "column",
      alignItems: "flex-start",
      gap: 2,
    },
    headerName: {
      fontSize: 26,
      lineHeight: 32,
      fontFamily: BRAND_FONT_FAMILY,
      color: colors.textOnBrand,
      includeFontPadding: false,
    },
    statsRow: { flexDirection: "row", marginTop: 20, gap: 12, paddingHorizontal: 4 },
    statItem: {
      flex: 1,
      backgroundColor: "rgba(255,255,255,0.14)",
      borderRadius: 18,
      paddingVertical: 16,
      alignItems: "center",
      borderWidth: 1.5,
      borderColor: "rgba(255,255,255,0.18)",
    },
    statNumber: { fontSize: 20, fontWeight: "800", color: colors.textOnBrand },
    statLabel: {
      fontSize: 11,
      color: "rgba(255,255,255,0.75)",
      fontWeight: "700",
      marginTop: 2,
    },
    noCoursesWrap: {
      flex: 1,
      justifyContent: "center",
      paddingHorizontal: 16,
      paddingVertical: 28,
    },
    noCoursesCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.borderSubtle,
      backgroundColor: colors.surface,
      paddingHorizontal: 20,
      paddingVertical: 24,
      alignItems: "center",
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
    },
    noCoursesMascot: {
      width: 44,
      height: 44,
      marginBottom: 10,
    },
    noCoursesTitle: {
      fontSize: 24,
      lineHeight: 32,
      color: colors.titlePrimary,
      fontFamily: BRAND_FONT_FAMILY,
      letterSpacing: 0.2,
    },
    noCoursesHeading: {
      marginTop: 8,
      fontSize: 17,
      fontWeight: "700",
      color: colors.textStrong,
      textAlign: "center",
    },
    noCoursesSubtitle: {
      marginTop: 6,
      fontSize: 14,
      color: colors.textSecondary,
      textAlign: "center",
      lineHeight: 20,
    },
    list: { padding: 16, paddingBottom: 96 },
    courseCard: {
      backgroundColor: colors.surface,
      borderRadius: 14,
      overflow: "hidden",
      shadowColor: colors.brandDeep,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
      marginBottom: 12,
    },
    cardAccent: { height: 4, backgroundColor: colors.brandPrimary },
    cardContent: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 10 },
    courseTitle: {
      fontSize: 17,
      lineHeight: 22,
      color: colors.titlePrimary,
      fontFamily: BRAND_FONT_FAMILY,
    },
    inlineActions: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "flex-end",
      gap: 8,
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 14,
      borderTopWidth: 1,
      borderTopColor: colors.borderSubtle,
    },
    inlineActionBtn: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 10,
      borderWidth: 1,
    },
    inlineEditBtn: { backgroundColor: colors.violetSoft, borderColor: colors.violetBorder },
    inlineDeleteBtn: { backgroundColor: colors.dangerSoft, borderColor: colors.dangerBorder },
    inlineActionText: { fontSize: 12, fontWeight: "700" },
    inlineEditText: { color: colors.violetText },
    inlineDeleteText: { color: colors.dangerText },
    courseDesc: { fontSize: 14, color: colors.textSecondary, lineHeight: 20, marginTop: 8 },
    courseDate: { fontSize: 12, color: colors.textMuted, marginTop: 10 },
    centered: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 32,
    },
    errorText: { fontSize: 16, color: colors.danger, marginBottom: 16, textAlign: "center" },
    retryBtn: {
      backgroundColor: colors.brandPrimary,
      paddingHorizontal: 24,
      paddingVertical: 10,
      borderRadius: 8,
    },
    retryText: { color: colors.textOnBrand, fontWeight: "600" },
    fab: {
      position: "absolute",
      bottom: 24,
      right: 20,
      borderRadius: 28,
      shadowColor: colors.brandPrimary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    fabGradient: {
      width: 56,
      height: 56,
      borderRadius: 28,
      justifyContent: "center",
      alignItems: "center",
    },
    fabText: { fontSize: 28, fontWeight: "600", color: colors.textOnBrand, marginTop: -2 },
  });
}

export type CoursesListStyles = ReturnType<typeof makeCoursesListStyles>;
