import { StyleSheet } from "react-native";

import { COLORS } from "../../lib/colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.canvas },
  headerGradient: { paddingTop: 56, paddingBottom: 20, paddingHorizontal: 20 },
  headerContent: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  headerGreeting: { fontSize: 14, color: "rgba(255,255,255,0.7)", fontWeight: "500" },
  headerName: { fontSize: 22, fontWeight: "800", color: COLORS.textOnBrand, marginTop: 2 },
  statsRow: { flexDirection: "row", marginTop: 20, gap: 12 },
  statItem: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  statNumber: { fontSize: 20, fontWeight: "800", color: COLORS.textOnBrand },
  statLabel: {
    fontSize: 11,
    color: "rgba(255,255,255,0.6)",
    fontWeight: "600",
    marginTop: 2,
  },
  list: { padding: 16, paddingBottom: 96 },
  courseCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 14,
    overflow: "hidden",
    shadowColor: COLORS.brandDeep,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 12,
  },
  cardAccent: { height: 4, backgroundColor: COLORS.brandPrimary },
  cardContent: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 10 },
  courseTitle: { fontSize: 17, fontWeight: "700", color: COLORS.textPrimary },
  inlineActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 14,
    borderTopWidth: 1,
    borderTopColor: COLORS.borderSubtle,
  },
  inlineActionBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
  },
  inlineEditBtn: { backgroundColor: COLORS.violetSoft, borderColor: COLORS.violetBorder },
  inlineDeleteBtn: { backgroundColor: COLORS.dangerSoft, borderColor: COLORS.dangerBorder },
  inlineActionText: { fontSize: 12, fontWeight: "700" },
  inlineEditText: { color: COLORS.violetText },
  inlineDeleteText: { color: COLORS.dangerText },
  courseDesc: { fontSize: 14, color: COLORS.textSecondary, lineHeight: 20, marginTop: 8 },
  courseDate: { fontSize: 12, color: COLORS.textMuted, marginTop: 10 },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
  },
  errorText: { fontSize: 16, color: COLORS.danger, marginBottom: 16, textAlign: "center" },
  retryBtn: {
    backgroundColor: COLORS.brandPrimary,
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 8,
  },
  retryText: { color: COLORS.textOnBrand, fontWeight: "600" },
  fab: {
    position: "absolute",
    bottom: 24,
    right: 20,
    borderRadius: 28,
    shadowColor: COLORS.brandPrimary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  fabGradient: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: "center",
    alignItems: "center",
  },
  fabText: { fontSize: 28, fontWeight: "600", color: COLORS.textOnBrand, marginTop: -2 },
});
