import { StyleSheet } from "react-native";

import { BRAND_FONT_FAMILY } from "../../lib/brand-font";
import type { AppColors } from "../../lib/colors";

export function makeMaterialScreenStyles(colors: AppColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.canvas,
    },
    backBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 4,
    },
    backBtnText: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.brandPrimary,
      flexShrink: 1,
    },
    centered: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.canvas,
      paddingHorizontal: 32,
    },
    errorText: {
      fontSize: 16,
      color: colors.danger,
      marginBottom: 16,
      textAlign: "center",
    },
    retryBtn: {
      backgroundColor: colors.brandPrimary,
      paddingHorizontal: 24,
      paddingVertical: 10,
      borderRadius: 8,
    },
    retryBtnText: {
      color: colors.textOnBrand,
      fontWeight: "600",
    },
    hero: {
      paddingTop: 20,
      paddingBottom: 24,
      paddingHorizontal: 20,
    },
    typeBadge: {
      alignSelf: "flex-start",
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 8,
      marginBottom: 12,
    },
    typeBadgeText: {
      fontSize: 12,
      fontWeight: "700",
    },
    heroTitle: {
      fontSize: 22,
      lineHeight: 29,
      color: colors.textOnBrand,
      marginBottom: 6,
      fontFamily: BRAND_FONT_FAMILY,
    },
    heroDate: {
      fontSize: 12,
      color: "rgba(255,255,255,0.5)",
    },
    pinBtn: {
      flexDirection: "row",
      alignItems: "center",
      alignSelf: "flex-start",
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    pinBtnNeutral: {
      borderColor: "rgba(255,255,255,0.34)",
      backgroundColor: "rgba(255,255,255,0.14)",
    },
    pinBtnDanger: {
      borderColor: "rgba(253,164,175,0.45)",
      backgroundColor: "rgba(190,24,93,0.2)",
    },
    pinBtnText: {
      fontSize: 12,
      fontWeight: "700",
      color: colors.textOnBrand,
    },
    heroActions: {
      flexDirection: "row",
      gap: 12,
      marginTop: 14,
    },
    shareBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderColor: "rgba(255,255,255,0.34)",
      backgroundColor: "rgba(255,255,255,0.14)",
    },
    shareBtnText: {
      fontSize: 12,
      fontWeight: "700",
      color: colors.textOnBrand,
    },
    offlineBannerWrap: {
      marginHorizontal: 16,
      marginTop: 12,
      marginBottom: 4,
    },
    contentCard: {
      backgroundColor: colors.surface,
      margin: 16,
      borderRadius: 14,
      padding: 20,
      shadowColor: colors.brandDeep,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
    },
    contentText: {
      fontSize: 15,
      color: colors.textPrimary,
      lineHeight: 24,
    },
    noContent: {
      fontSize: 14,
      color: colors.textMuted,
      textAlign: "center",
      paddingVertical: 12,
    },
    extractBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      backgroundColor: colors.brandPrimary,
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderRadius: 12,
    },
    extractBtnIcon: {
      fontSize: 18,
    },
    extractBtnText: {
      color: colors.textOnBrand,
      fontSize: 15,
      fontWeight: "600",
    },
    filePreviewCard: {
      backgroundColor: colors.surface,
      marginHorizontal: 16,
      marginBottom: 12,
      borderRadius: 14,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: colors.borderMuted,
      alignItems: "center",
      justifyContent: "center",
    },
    filePreviewImage: {
      width: "100%",
      height: 280,
      backgroundColor: colors.surfaceMuted,
    },
    filePreviewLoadingText: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: "600",
      paddingVertical: 16,
    },
    linkCard: {
      backgroundColor: colors.surface,
      marginHorizontal: 16,
      marginBottom: 12,
      borderRadius: 14,
      padding: 16,
      borderLeftWidth: 4,
      borderLeftColor: colors.link,
    },
    linkCardDisabled: {
      opacity: 0.72,
    },
    linkLabelRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      marginBottom: 4,
    },
    linkLabel: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.link,
    },
    linkUrl: {
      fontSize: 13,
      color: colors.textSecondary,
    },
    aiToolsBtn: {
      backgroundColor: colors.brandPrimary,
      marginHorizontal: 16,
      marginBottom: 16,
      borderRadius: 14,
      padding: 16,
      alignItems: "center",
      shadowColor: colors.brandDeep,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 10,
      elevation: 4,
    },
    aiToolsBtnText: {
      fontSize: 15,
      fontWeight: "700",
      color: colors.textOnBrand,
      letterSpacing: 0.5,
    },
    tagsCard: {
      backgroundColor: colors.surface,
      marginHorizontal: 16,
      borderRadius: 14,
      padding: 16,
    },
    tagsLabel: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.textTertiary,
      marginBottom: 8,
    },
    tagsRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    tag: {
      backgroundColor: colors.violetSoft,
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 8,
    },
    tagText: {
      fontSize: 13,
      color: colors.brandPrimary,
      fontWeight: "500",
    },
    bottomSpacer: {
      height: 32,
    },
  });
}
