import { StyleSheet } from "react-native";

import type { AppColors } from "../../lib/colors";

export function makeProfileTabStyles(colors: AppColors) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.canvas },
    centered: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: colors.canvas,
      paddingHorizontal: 32,
    },
    errorText: { fontSize: 16, color: colors.danger, marginBottom: 16, textAlign: "center" },
    retryBtn: {
      backgroundColor: colors.brandPrimary,
      paddingHorizontal: 24,
      paddingVertical: 10,
      borderRadius: 8,
    },
    retryBtnText: { color: colors.textOnBrand, fontWeight: "600" },
    hero: { alignItems: "center", paddingTop: 32, paddingBottom: 28 },
    avatarCircle: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: "rgba(255,255,255,0.2)",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 12,
    },
    avatarText: { fontSize: 28, fontWeight: "800", color: colors.textOnBrand },
    heroName: { fontSize: 22, fontWeight: "800", color: colors.textOnBrand, marginBottom: 8 },
    heroBadge: {
      backgroundColor: "rgba(255,255,255,0.15)",
      paddingHorizontal: 14,
      paddingVertical: 4,
      borderRadius: 8,
    },
    heroBadgeText: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textOnBrand,
      textTransform: "capitalize",
    },
    offlineBannerWrap: {
      marginHorizontal: 16,
      marginTop: 14,
      marginBottom: 4,
    },
    card: {
      backgroundColor: colors.surface,
      margin: 16,
      borderRadius: 14,
      padding: 20,
      shadowColor: colors.brandDeep,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
    },
    field: { marginBottom: 16 },
    fieldLabel: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 4,
    },
    fieldValue: { fontSize: 16, color: colors.textPrimary, fontWeight: "500" },
    editInput: {
      fontSize: 16,
      color: colors.textPrimary,
      borderWidth: 1.5,
      borderColor: colors.brandPrimary,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 10,
      backgroundColor: colors.surfaceHighlight,
    },
    actions: { marginHorizontal: 16, gap: 12 },
    settingsBtn: {
      borderWidth: 1.5,
      borderColor: colors.violetBorder,
      backgroundColor: colors.violetSoft,
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: "center",
    },
    settingsBtnText: { fontSize: 15, fontWeight: "700", color: colors.violetText },
    scanQrBtn: {
      borderWidth: 1.5,
      borderColor: colors.borderMuted,
      backgroundColor: colors.surface,
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: "center",
    },
    scanQrBtnText: { fontSize: 15, fontWeight: "700", color: colors.textSecondary },
    logoutBtn: {
      borderWidth: 1.5,
      borderColor: colors.dangerBorder,
      backgroundColor: colors.dangerSoft,
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: "center",
    },
    logoutBtnText: { fontSize: 15, fontWeight: "700", color: colors.dangerText },
    editBtn: {
      borderWidth: 2,
      borderColor: colors.brandPrimary,
      borderRadius: 12,
      paddingVertical: 14,
      alignItems: "center",
    },
    editBtnText: { fontSize: 16, fontWeight: "700", color: colors.brandPrimary },
    editActions: { flexDirection: "row", gap: 12 },
    cancelBtn: {
      flex: 1,
      borderWidth: 2,
      borderColor: colors.borderMuted,
      borderRadius: 12,
      paddingVertical: 14,
      alignItems: "center",
    },
    cancelBtnText: { fontSize: 16, fontWeight: "600", color: colors.textSecondary },
    saveBtn: { flex: 1, borderRadius: 12, overflow: "hidden" },
    saveBtnDisabled: { opacity: 0.6 },
    saveBtnGradient: { paddingVertical: 14, alignItems: "center" },
    saveBtnText: { fontSize: 16, fontWeight: "700", color: colors.textOnBrand },
    bottomSpacer: { height: 32 },
  });
}
