import { StyleSheet } from "react-native";

import { COLORS } from "../../lib/colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.canvas },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.canvas,
    paddingHorizontal: 32,
  },
  errorText: { fontSize: 16, color: COLORS.danger, marginBottom: 16, textAlign: "center" },
  retryBtn: {
    backgroundColor: COLORS.brandPrimary,
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 8,
  },
  retryBtnText: { color: COLORS.textOnBrand, fontWeight: "600" },
  hero: { alignItems: "center", paddingTop: 32, paddingBottom: 28 },
  avatarCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  avatarText: { fontSize: 28, fontWeight: "800", color: COLORS.textOnBrand },
  heroName: { fontSize: 22, fontWeight: "800", color: COLORS.textOnBrand, marginBottom: 8 },
  heroBadge: {
    backgroundColor: "rgba(255,255,255,0.15)",
    paddingHorizontal: 14,
    paddingVertical: 4,
    borderRadius: 8,
  },
  heroBadgeText: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.textOnBrand,
    textTransform: "capitalize",
  },
  offlineBannerWrap: {
    marginHorizontal: 16,
    marginTop: 14,
    marginBottom: 4,
  },
  card: {
    backgroundColor: COLORS.surface,
    margin: 16,
    borderRadius: 14,
    padding: 20,
    shadowColor: COLORS.brandDeep,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  field: { marginBottom: 16 },
  fieldLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  fieldValue: { fontSize: 16, color: COLORS.textPrimary, fontWeight: "500" },
  editInput: {
    fontSize: 16,
    color: COLORS.textPrimary,
    borderWidth: 1.5,
    borderColor: COLORS.brandPrimary,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: COLORS.surfaceHighlight,
  },
  actions: { marginHorizontal: 16, gap: 12 },
  settingsBtn: {
    borderWidth: 1.5,
    borderColor: COLORS.violetBorder,
    backgroundColor: COLORS.violetSoft,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  settingsBtnText: { fontSize: 15, fontWeight: "700", color: COLORS.violetText },
  logoutBtn: {
    borderWidth: 1.5,
    borderColor: COLORS.dangerBorder,
    backgroundColor: COLORS.dangerSoft,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
  },
  logoutBtnText: { fontSize: 15, fontWeight: "700", color: COLORS.dangerText },
  editBtn: {
    borderWidth: 2,
    borderColor: COLORS.brandPrimary,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  editBtnText: { fontSize: 16, fontWeight: "700", color: COLORS.brandPrimary },
  editActions: { flexDirection: "row", gap: 12 },
  cancelBtn: {
    flex: 1,
    borderWidth: 2,
    borderColor: COLORS.borderMuted,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  cancelBtnText: { fontSize: 16, fontWeight: "600", color: COLORS.textSecondary },
  saveBtn: { flex: 1, borderRadius: 12, overflow: "hidden" },
  saveBtnDisabled: { opacity: 0.6 },
  saveBtnGradient: { paddingVertical: 14, alignItems: "center" },
  saveBtnText: { fontSize: 16, fontWeight: "700", color: COLORS.textOnBrand },
  bottomSpacer: { height: 32 },
});
