import { StyleSheet } from "react-native";

import type { AppColors } from "../../lib/colors";

export function makeMaterialFormStyles(colors: AppColors) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.canvas },
    scrollContent: { padding: 16 },
    iconContainer: { alignItems: "center", marginVertical: 16 },
    iconCircle: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.violetSoft,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 10,
    },
    iconText: { fontSize: 24, fontWeight: "700", color: colors.brandPrimary },
    heading: { fontSize: 20, fontWeight: "800", color: colors.titlePrimary },
    errorBox: {
      backgroundColor: colors.dangerSoftAlt,
      borderWidth: 1,
      borderColor: colors.dangerBorderSoft,
      borderRadius: 10,
      padding: 12,
      marginBottom: 16,
    },
    errorText: { color: colors.danger, fontSize: 14, textAlign: "center" },
    typeRow: { flexDirection: "row", gap: 8, marginBottom: 16 },
    typeChip: {
      flex: 1,
      alignItems: "center",
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: colors.borderMuted,
      backgroundColor: colors.surface,
    },
    typeChipIcon: { fontSize: 16, fontWeight: "800", marginBottom: 2 },
    typeChipLabel: { fontSize: 11, fontWeight: "500", color: colors.textSecondary },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 14,
      padding: 20,
      shadowColor: colors.brandDeep,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
    },
    inputGroup: { marginBottom: 16 },
    inputLabel: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.textTertiary,
      marginBottom: 6,
      marginLeft: 2,
    },
    input: {
      backgroundColor: colors.surfaceSoft,
      borderWidth: 1.5,
      borderColor: colors.borderMuted,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 14,
      fontSize: 16,
      color: colors.textPrimary,
    },
    textArea: { minHeight: 220, paddingTop: 14 },
    inputFocused: { borderColor: colors.brandPrimary, backgroundColor: colors.surfaceHighlight },
    actions: { marginTop: 20, gap: 12 },
    submitBtn: { borderRadius: 12, overflow: "hidden" },
    disabledBtn: { opacity: 0.6 },
    submitGradient: { paddingVertical: 16, alignItems: "center" },
    submitBtnText: { color: colors.textOnBrand, fontSize: 16, fontWeight: "700" },
    cancelBtn: {
      borderWidth: 2,
      borderColor: colors.borderMuted,
      borderRadius: 12,
      paddingVertical: 14,
      alignItems: "center",
    },
    cancelBtnText: { fontSize: 16, fontWeight: "600", color: colors.textSecondary },
  });
}
